angular.module('SampleApp').controller 'HomeCtrl', ($scope, Endpoints, Element) ->
  $scope.home = "home"
  endpoints = Endpoints.get()
  listDiv = document.getElementById('list')

  showConnectionInfo = (s) ->
    listDiv.innerHTML = s
    listDiv.style.display = 'block'
    return

  hideConnectionInfo = ->
    listDiv.style.display = 'none'
    return

  connections = []

  updateConnections = (conn, remove) ->
    console.log conn
    if !remove
      connections.push conn
    else
      idx = -1
      i = 0
      while i < connections.length
        if connections[i] == conn
          idx = i
          break
        i++
      if idx != -1
        connections.splice idx, 1
    if connections.length > 0
      s = '<span><strong>Connections</strong></span><br/><br/><table><tr><th>Scope</th><th>Source</th><th>Target</th></tr>'
      j = 0
      while j < connections.length
        s = s + '<tr><td>' + connections[j].scope + '</td>' + '<td>' + connections[j].sourceId + '</td><td>' + connections[j].targetId + '</td></tr>'
        j++
      showConnectionInfo s
    else
      hideConnectionInfo()
    return

  jsPlumb.ready ->
    instance = Element.get()
    # suspend drawing and initialise.
    instance.batch ->
      Element.initialize()

      # instance.addEndpoint jsPlumb.getSelector('.drag-drop-demo .window'), endpoints.type

      # hideLinks = jsPlumb.getSelector('.drag-drop-demo .hide')
      # instance.on hideLinks, 'click', (e) ->
      #   instance.toggleVisible @getAttribute('rel')
      #   jsPlumbUtil.consume e
      #   return
      # dragLinks = jsPlumb.getSelector('.drag-drop-demo .drag')
      # instance.on dragLinks, 'click', (e) ->
      #   s = instance.toggleDraggable(@getAttribute('rel'))
      #   @innerHTML = if s then 'disable dragging' else 'enable dragging'
      #   jsPlumbUtil.consume e
      #   return
      # detachLinks = jsPlumb.getSelector('.drag-drop-demo .detach')
      # instance.on detachLinks, 'click', (e) ->
      #   instance.detachAllConnections @getAttribute('rel')
      #   jsPlumbUtil.consume e
      #   return
      instance.on document.getElementById('clear'), 'click', (e) ->
        instance.detachEveryConnection()
        showConnectionInfo ''
        jsPlumbUtil.consume e
        return
      return
    jsPlumb.fire 'jsPlumbDemoLoaded', instance
    return
  return

# ---
# generated by js2coffee 2.1.0
